### ISSUE TITLE
Title and subtitle are too small

### ISSUE THREAD

**Issue by EvgeniiaVak** [Romex91/self-help-sheets#4]
<img width="1440" alt="Screen Shot 2020-10-27 at 6 57 26 PM" src="https://user-images.githubusercontent.com/27793901/97298640-4eb37480-1886-11eb-9ebb-d3e6d0eeee33.png">
Even "Settings" text is larger.

**Comment by Romex91** [comment]
It doesn't look good if you increase the size:

![image](https://user-images.githubusercontent.com/9845705/97400119-262c8880-1921-11eb-9480-bad63f04e4ec.png)

I fink that removing 'Settings' will solve the problem
